language: java
jdk:
- oraclejdk8
- oraclejdk10
- openjdk8
- openjdk9
- openjdk10

deploy:
  provider: releases
  api_key:
    secure: FpedGUBOxQJk/UvbUK7znG6DgSnjf1lbick3CHEL7CktRCt3RTONdmC6tY5YeSFFqQY6uHGRvszV452UjA0+SBDUVLjIda6aPks38Vz6FzlAti+ggo/vbr68qmSyFcO27dFA+lyVVrCXzannVhNvybyJdwx/RS8YckEagaow6wDPMBB65GUqC9RDHs72Tg4lQt/B+en/VZ0npRVCbmCsHRVs/j2d+6BdaJlZfPSWDPFXMrZtPZc/IdDVhgff0UQo0Jv3rX+rp5MhlDEiiiQr/u4kUf+EnaFQUoT9iwg5LJsiIn77qyWwFA+KpLjvGgZkj0qAJT31eMEmiQeXwRE3PjAZPa4l8s8ohGWwOF41i+f8iSozhE+/BbbhUZNq3oICbOKJJeJR4eLJQBDcLHp5THWMBLQjfG0kqyKXzg+zKvBGDdcpkRmwx90rz3WOSNWh6//HvN0lLW0T6VB8Up9nnnzTaHf/DSHJtnkyjBCMhJCVOrgo3j2hxreTanZ9KCxoYxaArwCLl6aibuS3BLq1Zub0xp40QyiewgXPc0kZZgxyOaZnYJvDs48WFli9Csj5xngV2C4id080gz+gNRxjMJ5hHc+P+XCkTI+laDdqzPbJ8G+gzKLlpq41bx21OTvlj1DMsbrZp+eYu9IhnmZqMRzMRuI40K40RmasSV0e4AU=
  file: build/libs/myakka.jar
  skip_cleanup: true
  on:
    repo: DanySK/Courses---2018---Master-IoT-Example
    tags: true
